// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function flip(card) {
  if (card !== 0) {
    return /* Flipped */0;
  } else {
    return /* NotFlipped */1;
  }
}

export {
  flip ,
  
}
/* No side effect */
