// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as React                                    from "react";
import * as ReasonReact                              from "reason-react/src/ReasonReact.js";
import * as ParseAndRenderCard$LearningReasonmlPart2 from "./ParseAndRenderCard.bs.js";

var component = ReasonReact.statelessComponent("CardView");

function make(code, imageSource, flipped, onClick, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var className = flipped !== 0 ? "Card" : "Card flipped";
      return React.createElement("div", {
                  className: className,
                  onClick: onClick
                }, React.createElement("div", {
                      className: "Card front"
                    }, React.createElement("img", {
                          alt: ParseAndRenderCard$LearningReasonmlPart2.parseAndRender(code),
                          src: imageSource
                        })), React.createElement("div", {
                      className: "Card back"
                    }));
    });
  return newrecord;
}

export {
  component ,
  make      ,
  
}
/* component Not a pure module */
