// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Block               from "bs-platform/lib/es6/block.js";
import * as Curry               from "bs-platform/lib/es6/curry.js";
import * as ReasonReact         from "reason-react/src/ReasonReact.js";
import * as CardView$SimpleDeck from "./CardView.bs.js";

var component = ReasonReact.reducerComponent("CardContainer");

function make(code, imageSource, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return ReasonReact.element(/* None */0, /* None */0, CardView$SimpleDeck.make(code, imageSource, self[/* state */2][/* flipped */0], (function () {
                        return Curry._1(self[/* send */4], /* Flip */0);
                      }), /* array */[]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* flipped : true */1];
    });
  newrecord[/* reducer */12] = (function (_, state) {
      return /* Update */Block.__(0, [/* record */[/* flipped */1 - state[/* flipped */0]]]);
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.code, jsProps.imageSource, /* array */[]);
      }));

export {
  component ,
  make      ,
  $$default ,
  $$default   as default,
  
}
/* component Not a pure module */
