// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function parseAndRenderSuit(suitStr) {
  switch (suitStr) {
    case "C" : 
        return /* Some */["Clubs"];
    case "D" : 
        return /* Some */["Diamonds"];
    case "H" : 
        return /* Some */["Hearts"];
    case "S" : 
        return /* Some */["Spades"];
    default:
      return /* None */0;
  }
}

function parseAndRenderValue(valueStr) {
  switch (valueStr) {
    case "10" : 
        return /* Some */["Ten"];
    case "2" : 
        return /* Some */["Two"];
    case "3" : 
        return /* Some */["Three"];
    case "4" : 
        return /* Some */["Four"];
    case "5" : 
        return /* Some */["Five"];
    case "6" : 
        return /* Some */["Six"];
    case "7" : 
        return /* Some */["Seven"];
    case "8" : 
        return /* Some */["Eight"];
    case "9" : 
        return /* Some */["Nine"];
    case "A" : 
        return /* Some */["Ace"];
    case "J" : 
        return /* Some */["Jack"];
    case "K" : 
        return /* Some */["King"];
    case "Q" : 
        return /* Some */["Queen"];
    default:
      return /* None */0;
  }
}

function parseAndRenderCard(cardStr) {
  var length = cardStr.length;
  var suitStr = cardStr.slice(length - 1 | 0);
  var valueStr = cardStr.slice(0, length - 1 | 0);
  var renderedSuit = parseAndRenderSuit(suitStr);
  var renderedValue = parseAndRenderValue(valueStr);
  if (renderedValue && renderedSuit) {
    return renderedValue[0] + (" of " + renderedSuit[0]);
  } else {
    return "-- unknown card --";
  }
}

console.log(parseAndRenderCard("QC"));

exports.parseAndRenderSuit  = parseAndRenderSuit;
exports.parseAndRenderValue = parseAndRenderValue;
exports.parseAndRenderCard  = parseAndRenderCard;
/*  Not a pure module */
